format = """
[ ](bg:#222a44)[ ](bg:#3b4978)[ ](bg:#6577b3)\
$username\
[](fg:#a3aed2 bg:#769ff0)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$python\
$php\
$rust\
$nodejs\
$golang\
[](fg:#212736 bg:#1d2230)\
$time\
$cmd_duration\
[](fg:#1d2230)
 $character"""

[username]
disabled = false
show_always = true
style_user = 'bg:#a3aed2 fg:#090c0c'
style_root = 'bg:#a3aed2 fg:#090c0c'
format = '[ $user ]($style)'

[directory]
style = 'fg:#e3e5e5 bg:#769ff0'
read_only = 'RO'
read_only_style = 'bold fg:#ff0000 bg:#769ff0'
fish_style_pwd_dir_length = 3
format = '[ $path ]($style)[$read_only]($read_only_style)'

[git_branch]
symbol = 'Git'
style = 'fg:#769ff0 bg:#394260'
format = '[ $symbol $branch ]($style)'

[git_status]
style = 'fg:#769ff0 bg:#394260'
format = '[($all_status$ahead_behind )]($style)'

[python]
symbol = 'Py'
style = 'fg:#769ff0 bg:#212736'
format = '[ $symbol( $version)( \($virtualenv\)) |]($style)'

[php]
symbol = 'PHP'
style = 'fg:#769ff0 bg:#212736'
format = '[ $symbol( $version) |]($style)'

[lua]
symbol = 'Lua'
style = 'fg:#769ff0 bg:#212736'
format = '[ $symbol( $version) |]($style)'

[nodejs]
symbol = 'Node'
style = 'fg:#769ff0 bg:#212736'
format = '[ $symbol( $version) |]($style)'

[rust]
symbol = 'Rust'
style = 'fg:#769ff0 bg:#212736'
format = '[ $symbol( $version) |]($style)'

[golang]
symbol = 'Go'
style = 'fg:#769ff0 bg:#212736'
format = '[ $symbol( $version) |]($style)'

[time]
disabled = false
style = 'fg:#a0a9cb bg:#1d2230'
format = '[ $time ]($style)'

[cmd_duration]
style = 'fg:#a0a9cb bg:#1d2230'
show_milliseconds = true
format = '[ The last command took $duration ]($style)'
