# Enable Vi mode in Bash command line edit.
set -o vi

# Don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# For setting history length see HISTSIZE and HISTFILESIZE in bash(1)
# HISTSIZE=1000
HISTFILESIZE=2000

# Set minicom startup options.
export MINICOM='-c on'
